### ISSUE TITLE
Does not work in latest Chrome (83.0.4103.61)

### ISSUE THREAD

**Issue by ekuiter** [kbumsik/opus-media-recorder#26] opened 2020-05-30 08:04 UTC
Since the latest Chrome update, opus-media-recorder (with default options) no longer works. On at least five different devices with different operating systems we get the following error:

```
OpusMediaRecorder.js:227 Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already detached.
    at EventTarget._postMessageToWorker (webpack:///./node_modules/opus-media-recorder/OpusMediaRecorder.js?:227:21)
    at ScriptProcessorNode.processor.onaudioprocess (webpack:///./node_modules/opus-media-recorder/OpusMediaRecorder.js?:336:12)
_postMessageToWorker @ OpusMediaRecorder.js:227
processor.onaudioprocess @ OpusMediaRecorder.js:336
```

One week ago everything was working fine. As a workaround, we use Firefox for now. Is this fixable? I understand that `ScriptProcessorNode` was deprecated, could that be the issue?

**Comment by thiagoamarante** [comment] 2020-06-02 14:53
https://github.com/kbumsik/opus-media-recorder/issues/25
Duplicate of #25

**Comment by kbumsik** [comment] 2020-06-03 12:24
Thanks for reporting. It looks like a duplicate of #25. I will try to resolve the issue this weekend.

**Closed by kbumsik** 2020-06-03 12:24 UTC
